export const TIMER_CONFIG = {
  dsa: {
    easy: 20 * 60,
    medium: 35 * 60,
    hard: 45 * 60,
  },
  hld: {
    default: 45 * 60,
  },
  lld: {
    default: 60 * 60,
  },
} as const;

export const HLD_PROMPTS = [
  // --- EASY ---
  {
    id: "url-shortener",
    title: "Design a URL Shortener",
    prompt: "Design a URL shortening service like bit.ly or TinyURL that can handle 10M daily active users.",
    requirements: [
      "Handle 100K requests per second",
      "Short URLs should be unique and non-guessable",
      "Redirects should happen in < 100ms",
      "Support custom short URLs",
      "Track analytics (click count, geolocation)",
    ],
    difficulty: "easy" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/bitly",
    referenceLabel: "Hello Interview",
  },
  {
    id: "dropbox",
    title: "Design a File Storage Service (Dropbox)",
    prompt: "Design a cloud-based file storage service like Dropbox that allows users to store, sync, and share files across devices.",
    requirements: [
      "Users can upload and download files from any device",
      "Users can share files with other users",
      "Files sync automatically across all user devices",
      "Support files as large as 50GB",
      "Highly available with strong durability guarantees",
    ],
    difficulty: "easy" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/dropbox",
    referenceLabel: "Hello Interview",
  },
  // --- MEDIUM ---
  {
    id: "notification-system",
    title: "Design a Notification System",
    prompt: "Design a real-time notification system for a social media platform.",
    requirements: [
      "Send notifications to 100M users",
      "Real-time delivery (< 1 second latency)",
      "Support multiple notification types (likes, comments, messages)",
      "Users can subscribe to notification channels",
      "Guarantee at-least-once delivery",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://systemdesign.one/notification-service/",
    referenceLabel: "System Design One",
  },
  {
    id: "cache-system",
    title: "Design a Distributed Cache",
    prompt: "Design a distributed caching system similar to Redis or Memcached.",
    requirements: [
      "Key-value store with expiration",
      "Distributed across multiple nodes",
      "Support LRU eviction",
      "Consistent hashing for scaling",
      "Handle node failures",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/distributed-cache",
    referenceLabel: "Hello Interview",
  },
  {
    id: "chat-system",
    title: "Design a Chat Application",
    prompt: "Design a real-time chat system supporting 10M concurrent users.",
    requirements: [
      "One-to-one and group messaging",
      "Real-time message delivery",
      "Message history and search",
      "User presence (online/offline status)",
      "Typing indicators",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/whatsapp",
    referenceLabel: "Hello Interview",
  },
  {
    id: "ticketmaster",
    title: "Design a Ticket Booking System (Ticketmaster)",
    prompt: "Design an online ticket booking platform like Ticketmaster supporting 10M users and high-traffic event launches.",
    requirements: [
      "Users can view and search for events",
      "Users can book tickets to events",
      "Prevent double-booking with strong consistency",
      "Handle high throughput for popular events (10M users, one event)",
      "Support seat selection and reservation hold",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/ticketmaster",
    referenceLabel: "Hello Interview",
  },
  // --- HARD ---
  {
    id: "search-engine",
    title: "Design a Search Engine",
    prompt: "Design a search engine that indexes and searches across billions of documents.",
    requirements: [
      "Index billions of web pages",
      "Return results in < 500ms",
      "Support full-text search with relevance ranking",
      "Handle misspellings and synonyms",
      "Distributed crawling and indexing",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/fb-post-search",
    referenceLabel: "Hello Interview",
  },
  {
    id: "video-platform",
    title: "Design a Video Streaming Platform",
    prompt: "Design a platform like YouTube that streams videos to millions of users.",
    requirements: [
      "Upload and transcode videos",
      "Stream to 10M concurrent users",
      "Support adaptive bitrate streaming",
      "CDN for global distribution",
      "Minimize startup time (< 2 seconds)",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/youtube",
    referenceLabel: "Hello Interview",
  },
  {
    id: "payment-system",
    title: "Design a Payment System",
    prompt: "Design a payment processing system for an e-commerce platform.",
    requirements: [
      "Handle transactions with strong consistency",
      "Support multiple payment methods",
      "Fraud detection and prevention",
      "High throughput (10K transactions/sec)",
      "Audit trail and dispute resolution",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/payment-system",
    referenceLabel: "Hello Interview",
  },
  {
    id: "recommendations",
    title: "Design a Recommendation System",
    prompt: "Design a recommendation engine for Netflix or Amazon.",
    requirements: [
      "Real-time personalization",
      "Handle cold-start problem for new users",
      "Support collaborative filtering",
      "A/B testing infrastructure",
      "Model serving at scale",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://netflixtechblog.com/system-architectures-for-personalization-and-recommendation-e081aa94b5d8",
    referenceLabel: "Netflix Tech Blog",
  },
  {
    id: "uber",
    title: "Design a Ride-Sharing App (Uber)",
    prompt: "Design a ride-sharing platform like Uber supporting 10M daily active users with real-time driver matching.",
    requirements: [
      "Riders can get fare estimates for a start/destination",
      "Riders can request a ride and be matched with a nearby driver in < 1 minute",
      "Drivers can accept/decline requests and navigate to pickup/drop-off",
      "Strong consistency in ride matching (no driver assigned to two rides)",
      "Handle frequent driver location updates at scale",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/uber",
    referenceLabel: "Hello Interview",
  },
  {
    id: "web-crawler",
    title: "Design a Web Crawler",
    prompt: "Design a distributed web crawler that can index 10 billion pages within 5 days.",
    requirements: [
      "Crawl the web starting from a set of seed URLs",
      "Extract and store text content from each page",
      "Fault-tolerant: resume crawling without losing progress on failure",
      "Polite crawling: respect robots.txt and avoid overloading servers",
      "Detect and avoid crawling duplicate content",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/web-crawler",
    referenceLabel: "Hello Interview",
  },
  {
    id: "ad-click-aggregator",
    title: "Design an Ad Click Aggregator",
    prompt: "Design a system that tracks ad clicks and provides real-time analytics to advertisers.",
    requirements: [
      "Users click on ads and are redirected to the advertiser's website",
      "Advertisers can query click metrics with 1-minute granularity",
      "Handle up to 10K clicks per second at peak",
      "Sub-second analytics query response time",
      "Prevent abuse from users clicking ads multiple times",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/ad-click-aggregator",
    referenceLabel: "Hello Interview",
  },
  {
    id: "top-k-videos",
    title: "Design YouTube Top-K Videos",
    prompt: "Design a system that tracks video view counts and serves top-K queries across different time windows.",
    requirements: [
      "Clients query top K videos (up to 1000 results)",
      "Support tumbling windows: 1 hour, 1 day, 1 month, and all-time",
      "At most 1 minute delay between a view event and tabulation",
      "Precise counts (no approximation allowed)",
      "Handle YouTube-scale write throughput",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/top-k",
    referenceLabel: "Hello Interview",
  },
  {
    id: "tinder",
    title: "Design a Dating App (Tinder)",
    prompt: "Design a matchmaking and swiping platform like Tinder for 20M daily active users.",
    requirements: [
      "Users create profiles with preferences (age range, interests, max distance)",
      "Users see a personalized stack of nearby profiles matching their preferences",
      "Users swipe right (yes) or left (no) on profiles",
      "A mutual right swipe triggers a match notification instantly",
      "Scale to 20M DAU with ~100 swipes per user per day",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/tinder",
    referenceLabel: "Hello Interview",
  },
  // === PRACHUB CREAM SET (company-tagged, real interview questions) ===
  // --- MEDIUM ---
  {
    id: "distributed-rate-limiter",
    title: "Design a Distributed Rate Limiter",
    prompt: "Design a multi-tenant distributed rate limiting service used by hundreds of internal teams to enforce per-user, per-API-key, and per-route quotas.",
    requirements: [
      "Support token bucket and sliding window algorithms",
      "Sub-millisecond decision latency at 1M requests/sec",
      "Allow per-tenant rules configurable at runtime without redeploy",
      "Survive Redis/cache node failures without dropping limits",
      "Expose metrics for rejection rate, hot keys, and tenant usage",
    ],
    difficulty: "medium" as const,
    companies: ["Google", "Meta", "Microsoft"],
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/distributed-rate-limiter",
    referenceLabel: "Hello Interview",
  },
  {
    id: "typeahead-autocomplete",
    title: "Design a Search Autocomplete (Typeahead) Service",
    prompt: "Design a search-as-you-type service that suggests top completions for a 1B-document index with sub-100ms p99 latency.",
    requirements: [
      "Return top-10 suggestions ranked by popularity + recency",
      "Refresh trending terms within 1 minute of trend change",
      "Personalize suggestions based on user locale and history",
      "Handle 50K QPS globally with regional caches",
      "Prefix matching tolerant to one typo or missing space",
    ],
    difficulty: "medium" as const,
    companies: ["Uber", "Microsoft", "Google"],
    referenceUrl: "https://systemdesignschool.io/problems/typeahead/solution",
    referenceLabel: "System Design School",
  },
  {
    id: "distributed-job-scheduler",
    title: "Design a Distributed Job Scheduler",
    prompt: "Design a cron-like distributed job scheduler that runs millions of recurring and one-off jobs reliably across a fleet of workers.",
    requirements: [
      "Cron expression and one-shot scheduling at second granularity",
      "Exactly-once execution under worker crashes and network partitions",
      "Backfill missed runs after extended downtime, configurable per job",
      "Job dependencies and DAG execution with retry/backoff policies",
      "Tenant-level isolation so noisy jobs cannot starve others",
    ],
    difficulty: "medium" as const,
    companies: ["Amazon", "Microsoft"],
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler",
    referenceLabel: "Hello Interview",
  },
  {
    id: "game-leaderboard",
    title: "Design a Real-Time Game Leaderboard",
    prompt: "Design a global leaderboard for a mobile game with 100M MAU showing top-100 global, regional, and friends-only rankings.",
    requirements: [
      "Update score and reflect in leaderboard within 5 seconds",
      "Read top-K and a player's neighbors (±50 ranks) in <50ms",
      "Multiple boards: all-time, weekly, daily, friends",
      "Anti-cheat: detect impossible score jumps before commit",
      "Scale write throughput to 200K score updates/sec at launch",
    ],
    difficulty: "medium" as const,
    companies: ["Meta", "Roblox", "Snapchat"],
    referenceUrl: "https://redis.io/tutorials/howtos/leaderboard/",
    referenceLabel: "Redis Labs",
  },
  {
    id: "hashtag-metrics-aggregator",
    title: "Design a Hashtag Metrics Aggregator (Twitter Trends)",
    prompt: "Design a system that ingests a firehose of social posts and surfaces trending hashtags with counts per region and time window.",
    requirements: [
      "Ingest 500K events/sec with at-least-once guarantees",
      "Trends for 1m, 5m, 1h, 1d windows per region and globally",
      "Detect bursts within 30 seconds of onset",
      "Approximate counting (HyperLogLog/Count-Min-Sketch) is acceptable",
      "Cold storage of raw events for 30 days for backfill",
    ],
    difficulty: "medium" as const,
    companies: ["Google", "Meta", "Twitter"],
    referenceUrl: "https://mecha-mind.medium.com/system-design-top-k-trending-hashtags-4e12de5bb846",
    referenceLabel: "Top-K Hashtags Article",
  },
  {
    id: "online-auction",
    title: "Design an Online Auction System (eBay)",
    prompt: "Design an online auction platform that handles millions of concurrent live auctions with strict bid ordering and fairness.",
    requirements: [
      "Strict total ordering of bids per auction; no double-winner",
      "Bid latency under 200ms p99 even on hot auctions (>10K watchers)",
      "Anti-sniping: extend close time if a bid arrives in the final seconds",
      "Reliable winner determination with audit trail",
      "Notify watchers in real time on outbid and new high bid",
    ],
    difficulty: "medium" as const,
    companies: ["Meta", "eBay", "Amazon"],
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/online-auction",
    referenceLabel: "Hello Interview",
  },
  {
    id: "log-analytics-service",
    title: "Design a Log Filtering and Analytics Service",
    prompt: "Design a log analytics service (Splunk/Datadog-like) that ingests 10TB/day of structured + unstructured logs and serves interactive queries.",
    requirements: [
      "Sub-5-second p95 query latency on 7-day retention window",
      "Full-text search plus structured filters on tags and ranges",
      "Real-time alerting on threshold and pattern rules",
      "Tiered storage: hot SSD (24h), warm SSD (7d), cold object store (90d)",
      "Multi-tenant isolation with per-tenant ingest and query quotas",
    ],
    difficulty: "medium" as const,
    companies: ["Amazon", "Microsoft", "Datadog"],
    referenceUrl: "https://www.splunk.com/en_us/blog/devops/debugging-microservices-with-distributed-tracing-and-real-time-log-analytics.html",
    referenceLabel: "Splunk Blog",
  },
  {
    id: "ad-frequency-capping",
    title: "Design an Ad Frequency Capping System",
    prompt: "Design a system that prevents an ad from being shown to the same user more than N times per day across a global ad network.",
    requirements: [
      "Decision latency under 10ms at ad-serving call time",
      "Caps per user × campaign × time-window (hour, day, lifetime)",
      "Eventually consistent counts acceptable if drift < 5%",
      "Handle 1M ad decisions/sec at peak",
      "Survive regional outages without violating global caps materially",
    ],
    difficulty: "medium" as const,
    companies: ["Netflix", "Meta", "Google"],
    referenceUrl: "https://netflixtechblog.com/behind-the-scenes-building-a-robust-ads-event-processing-pipeline-e4e86caf9249",
    referenceLabel: "Netflix Tech Blog",
  },
  {
    id: "viewing-history-service",
    title: "Design a Viewing History and Resume Service (Netflix)",
    prompt: "Design a service that records what every user watched, when, and where they paused, so they can resume on any device.",
    requirements: [
      "Record resume position every 30 seconds during playback",
      "Read latest position cross-device within 5 seconds of writing",
      "Retain full history for 2 years; recent 90 days in hot tier",
      "Handle 100M MAU with avg 3 active streams per user",
      "Privacy: per-user delete must propagate within 30 days",
    ],
    difficulty: "medium" as const,
    companies: ["Netflix", "Google", "Amazon"],
    referenceUrl: "https://netflixtechblog.com/netflixs-viewing-data-how-we-know-where-you-are-in-house-of-cards-608dd61077da",
    referenceLabel: "Netflix Tech Blog",
  },
  {
    id: "mobile-model-quota",
    title: "Design a Mobile AI Model Usage Quota Service",
    prompt: "Design a quota service that enforces per-user, per-device, and per-feature usage limits for on-device + cloud LLM features in a mobile app.",
    requirements: [
      "Quota decisions within 50ms including offline cache",
      "Daily, monthly, and lifetime quotas with grace periods",
      "Tiered limits by subscription level, refreshable mid-cycle",
      "Reconcile offline usage when device reconnects",
      "Fraud-resistant: prevent device reset abuse via signed receipts",
    ],
    difficulty: "medium" as const,
    companies: ["Apple", "OpenAI", "Anthropic"],
    referenceUrl: "https://www.truefoundry.com/blog/rate-limiting-in-llm-gateway",
    referenceLabel: "TrueFoundry",
  },
  {
    id: "secure-copilot-api",
    title: "Design a Secure Copilot API",
    prompt: "Design a public-facing AI Copilot API that serves enterprise customers with strict auth, tenant isolation, and prompt/response auditing.",
    requirements: [
      "Per-tenant API keys with scoped permissions and rotation",
      "Tenant data isolation: prompts never cross tenant boundaries",
      "Full audit log of prompts and responses, queryable for 90 days",
      "PII redaction layer before model invocation, configurable per tenant",
      "Rate limiting and abuse detection at API gateway",
    ],
    difficulty: "medium" as const,
    companies: ["Microsoft", "GitHub", "Anthropic"],
    referenceUrl: "https://www.solo.io/blog/protect-your-ai-powered-apps-with-tiered-rate-limiting-in-gloo-ai-gateway",
    referenceLabel: "Solo.io",
  },
  {
    id: "org-chart-subordinate-count",
    title: "Design a Read-Heavy Org Chart Subordinate Counter",
    prompt: "Design a service that returns the total subordinate count for any employee in an org chart of 500K employees with millions of reads/day.",
    requirements: [
      "Sub-50ms p99 read latency for any node's recursive count",
      "Org changes (hire, transfer, terminate) reflected within 5 minutes",
      "Support 'team rollup' aggregations beyond count (avg tenure, etc.)",
      "Handle 10K writes/day and 5M reads/day",
      "Snapshot capability for point-in-time queries (audit, reporting)",
    ],
    difficulty: "medium" as const,
    companies: ["Microsoft", "Workday", "Meta"],
    referenceUrl: "https://creately.com/guides/hierarchical-structure-org-charts/",
    referenceLabel: "Creately Guide",
  },
  // --- HARD ---
  {
    id: "s3-object-storage",
    title: "Design an S3-like Object Storage Service",
    prompt: "Design a globally distributed object storage system supporting trillions of objects with 11-nines durability.",
    requirements: [
      "Put/get/delete objects up to 5TB each with multipart upload",
      "11-nines (99.999999999%) durability via cross-AZ replication",
      "Strong read-after-write consistency for new keys",
      "Sub-100ms p50 get latency for small objects",
      "Pluggable storage classes (standard, infrequent, glacier-tier)",
    ],
    difficulty: "hard" as const,
    companies: ["Amazon", "Google", "Microsoft"],
    referenceUrl: "https://aws.amazon.com/s3/",
    referenceLabel: "AWS S3",
  },
  {
    id: "key-management-service",
    title: "Design a Key Management Service (KMS)",
    prompt: "Design a multi-tenant managed key management service that mints, rotates, and audits cryptographic keys backed by HSMs.",
    requirements: [
      "Generate, rotate, disable, and destroy keys with tamper-evident audit",
      "Encrypt/decrypt API at 50K ops/sec per region with <20ms p99",
      "Per-key IAM policies; cross-account grants with explicit revocation",
      "FIPS 140-2 Level 3 HSM-backed master keys, never exportable",
      "Region failover without exposing key material to non-HSM systems",
    ],
    difficulty: "hard" as const,
    companies: ["Google", "Amazon", "Microsoft"],
    referenceUrl: "https://docs.aws.amazon.com/kms/latest/cryptographic-details/design-goals.html",
    referenceLabel: "AWS KMS Docs",
  },
  {
    id: "distributed-kv-store",
    title: "Design a Distributed Key-Value Store with Quorums",
    prompt: "Design a horizontally scalable key-value store (DynamoDB/Cassandra-like) with tunable consistency via quorum reads/writes.",
    requirements: [
      "Tunable R + W > N consistency knobs per request",
      "Consistent hashing with virtual nodes; rebalance without downtime",
      "Vector clocks or last-write-wins conflict resolution, configurable",
      "Anti-entropy via Merkle trees for replica repair",
      "Linear scale to PB-scale data and 1M ops/sec per cluster",
    ],
    difficulty: "hard" as const,
    companies: ["Amazon", "Google", "Apple"],
    referenceUrl: "https://www.hellointerview.com/learn/system-design/deep-dives/dynamodb",
    referenceLabel: "Hello Interview",
  },
  {
    id: "pubsub-replay-kafka",
    title: "Design a Pub-Sub Replay System (Kafka)",
    prompt: "Design a distributed publish-subscribe messaging system supporting topic-partitioned durable logs and arbitrary subscriber replay.",
    requirements: [
      "Durable ordered log per partition with configurable retention (hours to weeks)",
      "Subscribers can replay from any offset or timestamp",
      "At-least-once delivery, with idempotent producer option for exactly-once",
      "Horizontal scale via partition count; consumer groups rebalance on join/leave",
      "Throughput target: 10GB/sec ingest, 100K partitions per cluster",
    ],
    difficulty: "hard" as const,
    companies: ["Google", "LinkedIn", "Confluent"],
    referenceUrl: "https://www.hellointerview.com/learn/system-design/deep-dives/kafka",
    referenceLabel: "Hello Interview",
  },
  {
    id: "radius-top-k-search",
    title: "Design a Location-Based Radius Top-K Search (Yelp/Nearby)",
    prompt: "Design a system that returns the top-K results matching a query within a geographic radius (e.g. 'sushi within 2 miles, rated > 4').",
    requirements: [
      "Sub-200ms p99 latency for radius+filter+ranking queries",
      "Geo-index updates on business open/close within 5 minutes",
      "Combine geo proximity with relevance and personalized score",
      "Handle 50K QPS during peak (lunch, weekend evenings)",
      "Support spatial filters: bounding box, polygon, multi-stop route",
    ],
    difficulty: "hard" as const,
    companies: ["Meta", "Uber", "Yelp"],
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/yelp",
    referenceLabel: "Hello Interview",
  },
  {
    id: "iot-telemetry-pipeline",
    title: "Design an IoT Device Telemetry Pipeline",
    prompt: "Design a telemetry pipeline that ingests sensor data from 100M IoT devices, serving real-time dashboards and batch analytics.",
    requirements: [
      "Ingest 10M events/sec with at-least-once delivery",
      "Real-time path with <10s end-to-end latency for dashboards",
      "Batch path for hourly/daily aggregations and ML training",
      "Late-arriving data handled within 24-hour watermark window",
      "Device-side buffering and resync on connectivity loss",
    ],
    difficulty: "hard" as const,
    companies: ["Amazon", "Google", "Tesla"],
    referenceUrl: "https://aws.amazon.com/solutions/guidance/aws-iot-greengrass-foundations/",
    referenceLabel: "AWS IoT Guidance",
  },
  {
    id: "globally-consistent-metadata",
    title: "Design a Globally Consistent Metadata Service (Spanner)",
    prompt: "Design a globally distributed strongly-consistent metadata store backing services that need ACID transactions across continents.",
    requirements: [
      "External consistency: globally ordered transactions via synchronized clocks",
      "Multi-region writes with <500ms p99 commit latency",
      "Schema with secondary indexes and SQL-like queries",
      "Survive single-region outage without data loss or downtime",
      "Tenant isolation across thousands of internal services",
    ],
    difficulty: "hard" as const,
    companies: ["Google", "Amazon", "CockroachDB"],
    referenceUrl: "https://research.google/pubs/spanner-googles-globally-distributed-database-2/",
    referenceLabel: "Google Spanner Paper",
  },
  {
    id: "crash-resilient-file-system",
    title: "Design a Crash-Resilient Distributed File System (GFS/HDFS)",
    prompt: "Design a distributed file system optimized for large sequential writes and concurrent reads, surviving frequent commodity-hardware failures.",
    requirements: [
      "Chunk-based storage (64MB chunks), each replicated 3x across racks",
      "Append-mostly workload; atomic record append semantics",
      "Master/metadata server with hot standby and operation log",
      "Self-healing: detect chunk corruption and re-replicate automatically",
      "Petabyte scale, 1000+ chunkservers per cluster",
    ],
    difficulty: "hard" as const,
    companies: ["Netflix", "Google", "Meta"],
    referenceUrl: "https://research.google/pubs/the-google-file-system/",
    referenceLabel: "Google GFS Paper",
  },
  {
    id: "near-duplicate-video-detection",
    title: "Design Near-Duplicate Video Detection at Scale",
    prompt: "Design a system that detects near-duplicate videos against a 1B-video corpus when new uploads arrive (e.g. copyright, dedup).",
    requirements: [
      "Perceptual hashing/embedding pipeline for ingested videos",
      "ANN lookup against 1B-vector index in <1 second",
      "Tolerate transformations: re-encoding, cropping, watermarking",
      "Process new uploads at 1000 videos/min steady state",
      "Human-review queue for borderline matches with score >threshold",
    ],
    difficulty: "hard" as const,
    companies: ["Google", "Meta", "TikTok"],
    referenceUrl: "https://support.google.com/youtube/answer/2797370",
    referenceLabel: "YouTube Content ID",
  },
  {
    id: "ads-audience-targeting",
    title: "Design an Ads Audience Targeting System",
    prompt: "Design a system that builds and serves user audience segments for ad targeting based on demographics, behavior, and lookalike modeling.",
    requirements: [
      "Build segments from billions of user events using batch + streaming",
      "Serve segment-membership lookups in <5ms at ad-decision time",
      "Lookalike modeling: expand seed audience using behavioral similarity",
      "Privacy: support opt-out, GDPR/CCPA delete, and differential privacy options",
      "Daily segment refresh + real-time signals for recent activity",
    ],
    difficulty: "hard" as const,
    companies: ["Netflix", "Meta", "Google"],
    referenceUrl: "https://engineering.fb.com/2024/12/02/production-engineering/meta-andromeda-advantage-automation-next-gen-personalized-ads-retrieval-engine/",
    referenceLabel: "Engineering at Meta",
  },
  {
    id: "llm-serving",
    title: "Design a Large-Scale LLM Serving System (ChatGPT)",
    prompt: "Design an inference platform that serves an LLM (70B+ params) to millions of concurrent users with low latency and high throughput.",
    requirements: [
      "Streaming token output with <500ms time-to-first-token",
      "Continuous batching to maximize GPU utilization across requests",
      "Auto-scale model replicas across regions based on demand",
      "KV-cache management and prefix caching for repeated prompts",
      "Safety filtering (input + output) in <100ms additional latency",
    ],
    difficulty: "hard" as const,
    companies: ["Microsoft", "Anthropic", "OpenAI"],
    referenceUrl: "https://blog.vllm.ai/2023/06/20/vllm.html",
    referenceLabel: "vLLM Blog",
  },
  {
    id: "sandboxed-cloud-ide",
    title: "Design a Sandboxed Cloud IDE",
    prompt: "Design a browser-based IDE that gives every user an isolated container with code, terminal, and language tooling, started in seconds.",
    requirements: [
      "Cold-start a new sandbox in <3 seconds",
      "Strong isolation: gVisor/firecracker microVM per user",
      "Persist user filesystem across sessions with snapshot/restore",
      "Idle sandboxes hibernate after 15 min; warm-resume in <2 sec",
      "Egress controls + rate limits to prevent abuse from inside sandboxes",
    ],
    difficulty: "hard" as const,
    companies: ["Replit", "GitHub", "Microsoft"],
    referenceUrl: "https://firecracker-microvm.github.io/",
    referenceLabel: "Firecracker MicroVM",
  },
  {
    id: "hosted-notebook-platform",
    title: "Design a Hosted Notebook Platform (Databricks)",
    prompt: "Design a collaborative notebook platform where users run Spark/SQL/Python on attached clusters with versioning and sharing.",
    requirements: [
      "Attach/detach notebook to elastic compute clusters in seconds",
      "Real-time multi-user collaboration on a single notebook",
      "Persistent versioning with diff/rollback per cell",
      "Per-workspace cluster quotas and cost attribution",
      "Result caching to skip re-execution when inputs unchanged",
    ],
    difficulty: "hard" as const,
    companies: ["Databricks", "Snowflake", "Google"],
    referenceUrl: "https://www.databricks.com/blog/2022/06/25/software-engineering-best-practices-with-databricks-notebooks.html",
    referenceLabel: "Databricks Blog",
  },
];

export const LLD_PROMPTS = [
  // --- EASY ---
  {
    id: "snake-and-ladder",
    title: "Design Snake and Ladder Game",
    prompt: "Design an object-oriented system for a multiplayer Snake and Ladder game.",
    requirements: [
      "Board size is configurable (e.g., 100 squares)",
      "Multiple players can join a game",
      "Players roll a 6-sided die to move",
      "Snakes move players down, ladders move players up",
      "First player to reach the final square wins",
    ],
    difficulty: "easy" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/snake-and-ladder-problem-zgtac9lxwntg",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "tic-tac-toe",
    title: "Design Tic-Tac-Toe Game",
    prompt: "Design an object-oriented system for a two-player Tic-Tac-Toe game with a command-line interface.",
    requirements: [
      "Two players alternate placing X and O on a 3x3 grid",
      "Validate moves: only empty cells, correct player's turn",
      "Detect win condition (horizontal, vertical, diagonal) and draw",
      "Print the board state after every valid move",
      "Handle invalid moves gracefully with appropriate messages",
    ],
    difficulty: "easy" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-tic-tac-toe-smyfi9x064ry",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "2048-game",
    title: "Design 2048 Game",
    prompt: "Design an object-oriented system for the 2048 sliding tile game with a command-line interface.",
    requirements: [
      "Initialize a 4x4 grid with two tiles numbered 2 at random positions",
      "Players move tiles in 4 directions (up, down, left, right)",
      "Adjacent tiles with equal numbers merge into their sum",
      "Add a new tile (2 or 4) after each valid move",
      "Detect win (tile reaches 2048) and lose (no valid moves left)",
    ],
    difficulty: "easy" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-2048-game-osycd22zpn1y",
    referenceLabel: "WorkAt Tech",
  },
  // --- MEDIUM ---
  {
    id: "parking-lot",
    title: "Design a Parking Lot",
    prompt: "Design an object-oriented system for a multi-level parking lot.",
    requirements: [
      "Support multiple vehicle types (car, truck, motorcycle)",
      "Support multiple parking spot types (compact, large, handicapped)",
      "Issue a parking ticket at the entrance",
      "Calculate payment at the exit based on vehicle type and duration",
      "Track capacity and full status for each level",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-parking-lot-qm6hwq4wkhp8",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "splitwise",
    title: "Design Expense Sharing App (Splitwise)",
    prompt: "Design an object-oriented expense-sharing application where users can add expenses and split them among groups.",
    requirements: [
      "Users add expenses and split by EQUAL, EXACT amount, or PERCENT",
      "Track balances between all users (who owes how much to whom)",
      "Validate percent splits sum to 100% and exact splits sum to total",
      "Show all balances or balances for a specific user",
      "Round amounts to 2 decimal places consistently",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/splitwise-problem-0kp2yneec2q2",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "chess-validator",
    title: "Design a Chess Validator",
    prompt: "Design an object-oriented chess validator that enforces rules and tracks game state.",
    requirements: [
      "Initialize a chessboard with all pieces in correct starting positions",
      "Validate moves for each piece type (pawn, rook, bishop, knight, queen, king)",
      "Two players alternate turns; detect and reject invalid moves",
      "Detect check and checkmate conditions",
      "Display the board state after every valid move",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-chess-validator-to77d8oqpx2h",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "library-management",
    title: "Design a Library Management System",
    prompt: "Design an object-oriented system for a local library.",
    requirements: [
      "Search catalog by title, author, subject, or publication date",
      "Users can borrow, return, and reserve books",
      "Calculate fines for overdue books",
      "Support different user types (member, librarian)",
      "Send notifications for reservations and due dates",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-library-management-system-jgjrv8q8b136",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "trello",
    title: "Design Project Management Tool (Trello)",
    prompt: "Design an object-oriented project management system like Trello with boards, lists, and cards.",
    requirements: [
      "Create/delete boards with members, privacy settings (public/private), and auto-generated URLs",
      "Create/delete lists within boards; deleting a board cascades to its lists",
      "Create/delete cards within lists; assign/unassign members to cards",
      "Move cards across lists within the same board",
      "Show all boards, a single board, a single list, or a single card",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/trello-problem-t0nwwqt61buz",
    referenceLabel: "WorkAt Tech",
  },
  // --- HARD ---
  {
    id: "key-value-store",
    title: "Design an In-Memory Key-Value Store (Redis-like)",
    prompt: "Design a thread-safe, in-memory key-value store similar to Redis supporting structured attribute values.",
    requirements: [
      "Thread-safe get, put, delete, keys, and search operations",
      "Keys are strings; values are objects with named attributes (string, int, double, boolean)",
      "Search returns all keys matching a given attribute key-value pair",
      "Attribute types are fixed on first insertion; type mismatch throws an exception",
      "put replaces existing value; delete removes the key entirely",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-key-value-store-6gz6cq124k65",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "distributed-queue",
    title: "Design a Distributed Queue (Kafka-like)",
    prompt: "Design an in-memory distributed message queue system like Apache Kafka with topics, producers, and consumers.",
    requirements: [
      "Support multiple topics; producers publish string messages to topics",
      "Multiple consumers can subscribe to multiple topics",
      "Messages are delivered to all subscribers of a topic",
      "System is multi-threaded: messages can be produced and consumed in parallel",
      "Consumer prints '<consumer_id> received <message>' on receiving a message",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-distributed-queue-cuudq0sk0v14",
    referenceLabel: "WorkAt Tech",
  },
];
